{% set name = "setoptconf" %}
{% set version = "0.3.0" %}
{% set sha256 = "d2ecbd27c0c7d0d53990e2df98d9aad6490df8b75b71c621d8c441d6e91e3161" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  {% set pypi_name = name.replace("_", "-") %}
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python >=3
    - setuptools

  run:
    - python >=3
    - pyyaml

test:
  imports:
    - setoptconf
    - setoptconf.source

about:
  home: https://github.com/jayclassless/setoptconf
  license: MIT
  license_file: LICENSE
  summary: A module for retrieving program settings from various sources in a consistant method.

extra:
  recipe-maintainers:
    - jakirkham
