travis:
  secure:
    BINSTAR_TOKEN: OYQrcs/uSCGT9je+AQvEdsLhpg7DPk0Ib1og2SzD3E6f4pG2eepaHD0S0SVOBGs2+GUq/qynirmLHd6h2Zwlr7j8ohiVAMKSluFVIhLNhRh4WeAoRvQAkhMQDXSi9cCVnpdp/0oLlxMr/ImMSfE9GydLEIBExXrkNb4QF/cB/hiZn7hPKsgVdQf9dslk4/RxTT3e4CQT7RT1KkmCuSSibo0BFJgm2CpbyVqV60WKZj/Ohk8BxyLJOs+w9Y0oILuFzDTZnXSc7V+/cIRgR/pHSUBW2+B6PSOLxET2PDCnqpWQdzq9QEsN+X4D+xneI/0u4U7exDxlyUQMV0NrZqtd5n5Y3smAf5Ag95gy122DA33Vuq4MJqRJVHjyX5p2hJnSs/AO74/3j/SUV32405eRzMM1dgVOl+ywfnQnyqYP2DP+Q9WY3mIBvscIbzGsJm6w/z7Oy89oc6FV1lPg1SLUQjU26XjQWdTwWgbiRGCdoJ8myfvIN6PLlfggX6+U2AU6z5zNxa797f34F36fpt/tbbMUDSrjxh1rhR1udmiuPAZS8XwzsG3JgLsCR0uckdwU5BBQSjarfv1sT/IBx5YWl4r75L3YxXOE+SI8KsZlMb+gCYD3OpUMD9Xj0FOVPMazb21dFkWTiaNZC2emK0urhIIESO6S47FFRNcNU5okiuk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
